#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Load average
graph_vlabel load
load.label load
graph_args --base 1000 -l 0
graph_scale no
graph_category system
load.warning 10
load.critical 120
graph_info The load average of the machine describes how many processes are in the runqueue (scheduled to run "immediately").
load.info Average load for the five minutes.
EOM
        exit 0;;
esac

printf "load.value "

# FreeBSD doesn't know about /proc/loadavg, so we use sysctl instead
sysctl vm.loadavg | cut -d" " -f4
